### ISSUE TITLE
New Project Wizard: Build Failure

### ISSUE THREAD

**Issue by jonherke** [Optum/giraffle#22]
**Describe the bug**
Getting the following error when running the new project wizard Execution failed for task ':gsqlNewProject'.
> kotlin.io.NoSuchFileException: /var/folders/f3/tg1d4g617c5dbpdr6xncg2hnrg9w5m/T/gsqlPluginConfig6153035423516941993/output/.gitignore: The source file doesn't exist.

**To Reproduce**
12:52 $ gradle gsqlNewProject

> Configure project :
GSQL Plugin successfully applied to state_health

> Task :gsqlNewProject
[ant:echo] Welcome to the new project wizard. Please answer the following questions to start a new project.
[ant:input] Project Name: [myApp]
<-----------<-------------> 0% EXECUTING [11s]
[ant:input] Tigergraph Host: [localhost]
<-------------> 0% EXECUTING [13s]
[ant:input] Tigergraph Admin username: [tigergraph]
<-------------> 0% EXECUTING [14s]
<-------------> 0% EXECUTING [15s]
[ant:input] Tigergraph Admin password: [tigergraph]
<-------------> 0% EXECUTING [15s]
[ant:input] Tigergraph username: [tigergraph]
<-------------> 0% EXECUTING [16s]
[ant:input] Tigergraph password: [tigergraph]
<-------------> 0% EXECUTING [17s]
[ant:input] Do you want to support multiple environments? ([y], n)
<-------------> 0% EXECUTING [18s]
[ant:input] Do you want to use the Kotlin or Groovy DSL for you build? ([k], g)
<-------------> 0% EXECUTING [25s]

> Task :gsqlNewProject FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gsqlNewProject'.
> kotlin.io.NoSuchFileException: /var/folders/f3/tg1d4g617c5dbpdr6xncg2hnrg9w5m/T/gsqlPluginConfig6153035423516941993/output/.gitignore: The source file doesn't exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
1 actionable task: 1 executed

**Screenshots**
<img width="1510" alt="Screen Shot 2019-09-16 at 12 55 06 PM" src="https://user-images.githubusercontent.com/31220506/64981220-37cbe180-d881-11e9-9bc4-c683a15d5959.png">

**Comment by jmeekhof** [comment]
Can we re-test this? I believe it's been addressed by some of the recent releases.
