### ISSUE TITLE
Task to turn JSON (Visual Studio) schema export to GSQL script

### ISSUE THREAD

**Issue by jonherke** [Optum/giraffle#3]
If possible it would be great if we could turn the Schema export file into a GSQL script. Please contact me if you think this would be possible. I would love to help create such a task to contribute to the robust functionality of this plugin!

**Comment by jonherke** [comment]
*task* **JSONtoGSQL**
*description* This task will take the folder location of your JSON schema and convert it to a GSQL script

**Comment by jmeekhof** [comment]
I don't think this falls under the types of tasks that Giraffle does.
